### ISSUE TITLE
Missing `har-validator` causing yarn installs to fail

### ISSUE THREAD

**Issue by grxy** [cypress-io/request#14]
### Summary
The dependency on `har-validator` was removed in https://github.com/cypress-io/request/pull/11, but it is still referenced at https://github.com/cypress-io/request/blob/master/lib/har.js#L5

### Simplest Example to Reproduce

Install cypress as a dependency using `yarn`.

### Expected Behavior

`yarn` install succeeds.

### Current Behavior

`yarn` install fails with an error similar to the following:

```
[5/5] Building fresh packages...
--
  | error /var/www/node_modules/cypress: Command failed.
  | Exit code: 1
  | Command: node index.js --exec install
  | Arguments:
  | Directory: /var/www/node_modules/cypress
  | Output:
  | internal/modules/cjs/loader.js:905
  | throw err;
  | ^
  |  
  | Error: Cannot find module 'har-validator'
  | Require stack:
  | - /var/www/node_modules/@cypress/request/lib/har.js
  | - /var/www/node_modules/@cypress/request/request.js
  | - /var/www/node_modules/@cypress/request/index.js
  | - /var/www/node_modules/cypress/lib/tasks/download.js
  | - /var/www/node_modules/cypress/lib/tasks/install.js
  | - /var/www/node_modules/cypress/index.js
  | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  | at Function.Module._load (internal/modules/cjs/loader.js:746:27)
  | at Module.require (internal/modules/cjs/loader.js:974:19)
  | at require (internal/modules/cjs/helpers.js:93:18)
  | at Object.<anonymous> (/var/www/node_modules/@cypress/request/lib/har.js:5:16)
  | at Module._compile (internal/modules/cjs/loader.js:1085:14)
  | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  | at Module.load (internal/modules/cjs/loader.js:950:32)
  | at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  | at Module.require (internal/modules/cjs/loader.js:974:19)
  | at require (internal/modules/cjs/helpers.js:93:18)
  | at Object.<anonymous> (/var/www/node_modules/@cypress/request/request.js:23:11)
  | at Module._compile (internal/modules/cjs/loader.js:1085:14)
  | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  | at Module.load (internal/modules/cjs/loader.js:950:32)
  | at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  | code: 'MODULE_NOT_FOUND',
  | requireStack: [
  | '/var/www/node_modules/@cypress/request/lib/har.js',
  | '/var/www/node_modules/@cypress/request/request.js',
  | '/var/www/node_modules/@cypress/request/index.js',
  | '/var/www/node_modules/cypress/lib/tasks/download.js',
  | '/var/www/node_modules/cypress/lib/tasks/install.js',
  | '/var/www/node_modules/cypress/index.js'
  | ]
  | }


```

### Possible Solution

Reinstate `har-validator` as a dependency until its references can be updated or removed.

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             | 14.18.1
| npm              | N/A
| Operating System | macOS

**Comment by emilyrohrbough** [comment]
https://github.com/cypress-io/cypress/issues/19097

**Comment by JJ** [comment]
That package [is deprecated](https://www.npmjs.com/package/har-validator). It is probably a better alternative to either ditch the import and sentence or try to validate in some other way.

**Comment by CharlesStover** [comment]
Sharing my similar stack trace:

```
Error: @cypress/request tried to access har-validator, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: har-validator
Required by: @cypress/request@npm:2.88.8 (via ...\.yarn\cache\@cypress-request-npm-2.88.8-363036f3bd-a3dc34f492.zip\node_modules\@cypress\request\lib\)

Require stack:
- ...\.yarn\cache\@cypress-request-npm-2.88.8-363036f3bd-a3dc34f492.zip\node_modules\@cypress\request\lib\har.js
- ...\.yarn\cache\@cypress-request-npm-2.88.8-363036f3bd-a3dc34f492.zip\node_modules\@cypress\request\request.js
- ...\.yarn\cache\@cypress-request-npm-2.88.8-363036f3bd-a3dc34f492.zip\node_modules\@cypress\request\index.js
- ...\.yarn\unplugged\cypress-npm-9.1.0-0dc889cc56\node_modules\cypress\lib\tasks\download.js
- ...\.yarn\unplugged\cypress-npm-9.1.0-0dc889cc56\node_modules\cypress\lib\tasks\install.js
- ...\.yarn\unplugged\cypress-npm-9.1.0-0dc889cc56\node_modules\cypress\index.js
```
