### ISSUE TITLE
test-form-data.js fails on Node.js >= 20.x

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/request#47]
- Follow-on to https://github.com/cypress-io/request/issues/37

Version:

[@cypress/request@3.0.1](https://github.com/cypress-io/request/releases/tag/v3.0.1)

```bash
npm install yarn@latest -g
git clone https://github.com/cypress-io/request
cd request
yarn install
node ./tests/test-form-data.js
```

fails for Node.js ~~`20.8.0`~~ `20.12.1`
running on Ubuntu ~~`22.04.3`~~ `22.04.4` LTS.

The test succeeds with Node.js ~~`18.18.1`~~ `18.20.1`LTS.

Other tests called by `yarn test` succeed on Node.js `18.x` and `20.x`

## Logs

```text
$ node ./tests/test-form-data.js
TAP version 13
# multipart formData
ok 1 should be truthy
ok 2 should be truthy
ok 3 should be truthy
ok 4 should be truthy
ok 5 should be truthy
ok 6 should be truthy
ok 7 should be truthy
ok 8 should be truthy
ok 9 should be truthy
ok 10 should be truthy
ok 11 should be truthy
ok 12 should be truthy
ok 13 should be truthy
ok 14 should be truthy
ok 15 should be truthy
ok 16 should be truthy
ok 17 should be truthy
ok 18 should be truthy
ok 19 should be equal
ok 20 should be equal
ok 21 should be equivalent
# multipart formData + JSON
ok 22 should be truthy
ok 23 should be truthy
ok 24 should be truthy
ok 25 should be truthy
ok 26 should be truthy
ok 27 should be truthy
ok 28 should be truthy
ok 29 should be truthy
ok 30 should be truthy
ok 31 should be truthy
ok 32 should be truthy
ok 33 should be truthy
ok 34 should be truthy
ok 35 should be truthy
ok 36 should be truthy
ok 37 should be truthy
ok 38 should be truthy
ok 39 should be truthy
ok 40 should be equal
ok 41 should be equal
ok 42 should be equivalent
# multipart formData + basic auth
ok 43 should be equal
not ok 44 should be equal
  ---
    operator: equal
    expected: 200
    actual:   400
    at: Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:114:9)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:443:48)
          at Test.bound [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Test.equal (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:604:7)
          at Test.bound [as equal] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:114:9)
          at self.callback (/home/mike/github/cypress-io/request/request.js:183:22)
          at Request.emit (node:events:514:28)
          at Request.<anonymous> (/home/mike/github/cypress-io/request/request.js:1156:10)
          at Request.emit (node:events:514:28)
          at IncomingMessage.<anonymous> (/home/mike/github/cypress-io/request/request.js:1070:12)
  ...
not ok 45 should be equivalent
  ---
    operator: deepEqual
    expected: 'done'
    actual:   ''
    at: Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:115:9)
    stack: |-
      Error: should be equivalent
          at Test.assert [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:443:48)
          at Test.bound [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Test.tapeDeepEqual (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:641:7)
          at Test.bound [as deepEqual] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:115:9)
          at self.callback (/home/mike/github/cypress-io/request/request.js:183:22)
          at Request.emit (node:events:514:28)
          at Request.<anonymous> (/home/mike/github/cypress-io/request/request.js:1156:10)
          at Request.emit (node:events:514:28)
          at IncomingMessage.<anonymous> (/home/mike/github/cypress-io/request/request.js:1070:12)
  ...

1..45
# tests 45
# pass  43
# fail  2
```

**Comment by jennifer-shehane** [comment]
This test does not fail with Node 22: https://github.com/cypress-io/request/pull/58 Closing.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

I am unable to confirm that this issue is resolved as I'm still seeing the test failing for Node.js 20 and 22 when I run it locally.

## CircleCI

CircleCI is testing on the obsolete Node.js 14 version using the deprecated image `circleci/node:14`

https://github.com/cypress-io/request/blob/d348a036fb6a0642ab2a9cdf4c05b2aaed05a4c9/.circleci/config.yml#L3-L19

## GitHub Actions

GitHub Actions tests only on Node.js `18.16`

https://github.com/cypress-io/request/blob/d348a036fb6a0642ab2a9cdf4c05b2aaed05a4c9/.github/workflows/yarn.yaml#L4-L13

**Comment by MikeMcC399** [comment]
```text
$ node -v
v22.8.0
$ node ./tests/test-form-data.js
(node:7746) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
TAP version 13
# multipart formData
(node:7746) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
ok 1 should be truthy
ok 2 should be truthy
ok 3 should be truthy
ok 4 should be truthy
ok 5 should be truthy
ok 6 should be truthy
ok 7 should be truthy
ok 8 should be truthy
ok 9 should be truthy
ok 10 should be truthy
ok 11 should be truthy
ok 12 should be truthy
ok 13 should be truthy
ok 14 should be truthy
ok 15 should be truthy
ok 16 should be truthy
ok 17 should be truthy
ok 18 should be truthy
ok 19 should be equal
ok 20 should be equal
ok 21 should be equivalent
# multipart formData + JSON
ok 22 should be truthy
ok 23 should be truthy
ok 24 should be truthy
ok 25 should be truthy
ok 26 should be truthy
ok 27 should be truthy
ok 28 should be truthy
ok 29 should be truthy
ok 30 should be truthy
ok 31 should be truthy
ok 32 should be truthy
ok 33 should be truthy
ok 34 should be truthy
ok 35 should be truthy
ok 36 should be truthy
ok 37 should be truthy
ok 38 should be truthy
ok 39 should be truthy
ok 40 should be equal
ok 41 should be equal
ok 42 should be equivalent
# multipart formData + basic auth
ok 43 should be equal
not ok 44 should be equal
  ---
    operator: equal
    expected: 200
    actual:   400
    at: Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:114:9)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:443:48)
          at Test.bound [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Test.equal (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:604:7)
          at Test.bound [as equal] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:114:9)
          at self.callback (/home/mike/github/cypress-io/request/request.js:183:22)
          at Request.emit (node:events:520:28)
          at Request.<anonymous> (/home/mike/github/cypress-io/request/request.js:1156:10)
          at Request.emit (node:events:520:28)
          at IncomingMessage.<anonymous> (/home/mike/github/cypress-io/request/request.js:1070:12)
  ...
not ok 45 should be equivalent
  ---
    operator: deepEqual
    expected: 'done'
    actual:   ''
    at: Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:115:9)
    stack: |-
      Error: should be equivalent
          at Test.assert [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:443:48)
          at Test.bound [as _assert] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Test.tapeDeepEqual (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:641:7)
          at Test.bound [as deepEqual] (/home/mike/github/cypress-io/request/node_modules/tape/lib/test.js:89:17)
          at Request._callback (/home/mike/github/cypress-io/request/tests/test-form-data.js:115:9)
          at self.callback (/home/mike/github/cypress-io/request/request.js:183:22)
          at Request.emit (node:events:520:28)
          at Request.<anonymous> (/home/mike/github/cypress-io/request/request.js:1156:10)
          at Request.emit (node:events:520:28)
          at IncomingMessage.<anonymous> (/home/mike/github/cypress-io/request/request.js:1070:12)
  ...

1..45
# tests 45
# pass  43
# fail  2
```
