### ISSUE TITLE
Error with cypress e2e test after dependency update 

### ISSUE THREAD

**Issue by maumau27** [cypress-io/request#78]
I encountered an error when running e2e test unit after an update of a dependency.
I was using @cypress ^13.0.0; that was using @cypress/request 3.0.5 as a dependency. 
Two days ago, I started having problems. I found that the dependency @cypress/request changed to 3.0.6.
And by forcing the use of @cypress/request 3.0.5, the error was fixed.

The error was the following:

`Error: Webpack Compilation Error
Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at handle (dist/my-app/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (dist/my-app/node_modules/webpack/lib/Compiler.js:498:32)
    at dist/my-app/node_modules/webpack/lib/Compiler.js:576:17
    at dist/my-app/node_modules/webpack/lib/HookWebpackError.js:67:2
    at Hook.eval [as callAsync] (eval at create (dist/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (dist/my-app/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (dist/my-app/node_modules/webpack/lib/Cache.js:126:37)
    at dist/my-app/node_modules/webpack/lib/Compiler.js:572:19
    at Hook.eval [as callAsync] (eval at create (dist/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (dist/my-app/node_modules/tapable/lib/Hook.js:18:14)
    at dist/my-app/node_modules/webpack/lib/Compiler.js:568:23
    at Compiler.emitRecords (dist/my-app/node_modules/webpack/lib/Compiler.js:1044:4)
    at dist/my-app/node_modules/webpack/lib/Compiler.js:558:11
    at dist/my-app/node_modules/webpack/lib/Compiler.js:1007:14
    at Hook.eval [as callAsync] (eval at create (dist/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (dist/my-app/node_modules/tapable/lib/Hook.js:18:14)
    at dist/my-app/node_modules/webpack/lib/Compiler.js:1004:27
    at dist/my-app/node_modules/neo-async/async.js:2818:7
    at done (dist/my-app/node_modules/neo-async/async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (dist/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (dist/my-app/node_modules/tapable/lib/Hook.js:18:14)
    at dist/my-app/node_modules/webpack/lib/Compiler.js:833:33
    at dist/my-app/node_modules/graceful-fs/graceful-fs.js:143:16
    at dist/.cache/Cypress/13.0.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at dist/.cache/Cypress/13.0.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at dist/.cache/Cypress/13.0.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:192:23)`

My WebPack config is:

`module.exports = (on, config) => {
    const webpackPreprocessor = require('@cypress/webpack-batteries-included-preprocessor');
    const webpackOptions = webpackPreprocessor.defaultOptions.webpackOptions;

    webpackOptions.module.rules.unshift({
        test: /\.m?js$/,
        resolve: {
            fullySpecified: false,
        },
        use: {
            loader: 'babel-loader',
            options: {
                plugins: ['@angular/compiler-cli/linker/babel'],
                compact: false,
                cacheDirectory: true,
            },
        },
    });

    webpackOptions.module.rules.unshift({
        test: /\.node$/,
        resolve: {
            fullySpecified: false,
        },
        use: {
            loader: 'node-loader',
        },
    });

    on(
        'file:preprocessor',
        webpackPreprocessor({
            webpackOptions: webpackOptions,
            typescript: require.resolve('typescript'),
        })
    );

    return config;
};`

**Comment by MikeMcC399** [comment]
@maumau27 

Could you add information about the versions of other dependencies you are using:

```text
@angular
webpack
```

etc.

If the release of `@cypress/request@3.0.6` is causing a breaking change, it may need to be reverted and the change re-released as `@cypress/request@4.0.0` instead

**Comment by MikeMcC399** [comment]
@maumau27 

Thanks for the version information! It seems you are using Angular 14, for example `"@angular/core": "^14.3.0"`

According to https://angular.dev/reference/releases#actively-supported-versions

> Angular versions v2 to v15 are no longer supported.

I'm looking to see if the issue is reproducible using supported versions of Angular.

**Comment by maumau27** [comment]
@MikeMcC399 

Thanks for looking into it.
I will update the Angular version in the future.
In the mean time, I'm using version 3.0.5 of @cypress/request.
In case you re-release the version, I can revert that change.

**Comment by MikeMcC399** [comment]
@maumau27 

> Thanks for looking into it. I will update the Angular version in the future. 

Good idea!

(Unrelated, but I also notice that you're using an unsupported version ESLint v7, where currently ESLint v9 is the minimum.)

> In the mean time, I'm using version 3.0.5 of @cypress/request.

Also good!

>  In case you re-release the version, I can revert that change.

I can't speak for the Cypress.io team who own the package, as I'm external. I guess it will depend if there are significant compatibility issues reported by other users with supported dependencies. The update resolved a deprecation issue, so it was a necessary step forward. Anyway it is good that you reported your issue!

**Comment by maumau27** [comment]
@MikeMcC399 

Thanks for the support.

> (Unrelated, but I also notice that you're using an unsupported version ESLint v7, where currently ESLint v9 is the minimum.)

I will be looking into that. Thanks for the notice.

> I can't speak for the Cypress.io team who own the package, as I'm external. I guess it will depend if there are significant compatibility issues reported by other users with supported dependencies. The update resolved a deprecation issue, so it was a necessary step forward. Anyway it is good that you reported your issue!

Okay, I will be monoriting to see if there are any changes to the version.
Did you manage to reproduce the error in a supported version of angular? 

Thanks again for the quick response.

**Comment by maumau27** [comment]
@MikeMcC399 

I'm using node 16.18.1.

> According to https://angular.dev/reference/versions#unsupported-angular-versions Angular 14 needs Node.js 14 or 16 and these are no longer supported by Cypress.

I see, that's okay. Until I make the upgrade to a newer version of Angular, I can use the fixed version of @cypress/resources.
I wanted to report the issue just in case.
